spring:
  application:
    name: hospitalClinica 
  jpa:  ## DIRECTIVA Y CONFIGURACIONES DEL FRAMEWORK JPA
    show-sql : true # Muestra o pinta lo que hace jpa los querys
    database: mysql # lenguaje de los querys es mysql
    hibernate:
      ddl-auto: update # quieres actualizar la tabla cada vezx que se conecte
    properties:
      hibernate:
        format_sql: true # le da formato a los query
        dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:    url: jdbc:mysql://localhost:3306/hospitalclinica?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=America/Mexico_City
    username: root
    password: 
